### ISSUE TITLE
Local Cache is null

### ISSUE THREAD

**Issue by ytjdud** [EUM-kmu/Eum-Chat#10]
**KST 오후 6시 9분부터 첫 에러**

2024-05-14T09:09:09.130Z  WARN 1 --- [prod-eum-chat] [onPool-worker-6] c.g.b.caffeine.cache.BoundedLocalCache   : Exception thrown by removal listener

java.lang.NullPointerException: Cannot invoke "java.util.Queue.size()" because "messageQueue" is null
	at com.eum.haetsal.chat.global.cache.CacheConfig.commitMessageQueue(CacheConfig.java:46) ~[!/:0.0.1-SNAPSHOT]
	at com.eum.haetsal.chat.global.cache.CacheConfig.lambda$chatCache$0(CacheConfig.java:33) ~[!/:0.0.1-SNAPSHOT]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$notifyRemoval$1(BoundedLocalCache.java:422) ~[caffeine-3.1.8.jar!/:3.1.8]
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[na:na]
	
	
**KST 오후 9시**
	2024-05-14T11:00:33.596Z  INFO 1 --- [prod-eum-chat] [nio-8080-exec-7] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x000xee0x010x000x000xea0x030x030x900xfe0xa50xdeZ0xa30x1f>0xc70xb50x0860xbd0xaa0xae0xd00xb7.N0x0d0xda0xd5^0xec0xf50xef0xfe0xf00xf50x1f0xe30xb1 ]. HTTP method names must be tokens
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:407) ~[tomcat-embed-core-10.1.18.jar!/:na]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:264) ~[tomcat-embed-core-10.1.18.jar!/:na]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.18.jar!/:na]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896) ~[tomcat-embed-core-10.1.18.jar!/:na]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744) ~[tomcat-embed-core-10.1.18.jar!/:na]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.18.jar!/:na]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.18.jar!/:na]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.18.jar!/:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-10.1.18.jar!/:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
	

KST 오후 9시 35분부터 계속해서 뜬 에러, 이때 다같이 채팅방 확인하느라 에러 여러개 뜬 것으로 예상.
이후 서버 종료, 모든 메시지가 저장안됨.

**Comment by ytjdud** [comment]
추측2
말그대로 initialCapacity 를 넘어서서 LRU 정책에 의해 삭제되었다.

해결
.softValue() 는 그대로 두고, initialCapacity (와 .maximumSize 도 이참에) 를 재설정 한다.
